# Generated by Django 3.2.3 on 2021-08-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_cliente_usuario_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='max_casos',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
