# Generated by Django 3.2.3 on 2021-09-09 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_llaveregistro_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='llaveregistro',
            name='subkey',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='llaveregistro',
            name='key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
