# Generated by Django 3.2.3 on 2021-09-14 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_llaveregistro_archivo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llaveregistro',
            name='archivo',
        ),
    ]
