# Generated by Django 3.2.3 on 2021-09-14 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_llaveregistro_archivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='llaveregistro',
            old_name='archivo_id',
            new_name='archivo',
        ),
    ]
