# Generated by Django 3.2.3 on 2021-09-14 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_archivo_id_llaveregistro_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llaveregistro',
            name='archivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.archivoregistro'),
        ),
    ]
