# Generated by Django 3.2.3 on 2021-09-14 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_llaveregistro_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubllaveRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='llaveregistro',
            name='subkey',
        ),
    ]
