# Generated by Django 3.2.3 on 2021-09-14 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210913_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='subllaveregistro',
            name='key',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.llaveregistro'),
            preserve_default=False,
        ),
    ]
