# Generated by Django 3.2.3 on 2021-09-14 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_subllaveregistro_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subllaveregistro'),
        ),
    ]
