# Generated by Django 3.2.3 on 2021-09-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_registro_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llaveregistro',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='subllaveregistro',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
