# Generated by Django 3.2.3 on 2021-09-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_subllaveregistro_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='llaveregistro',
            name='datos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='llaveregistro',
            name='nombres',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='llaveregistro',
            name='subllaves',
            field=models.BooleanField(default=False),
        ),
    ]
