# Generated by Django 3.2.3 on 2021-09-26 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_registro_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='subkey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.subllaveregistro'),
        ),
    ]
