# Generated by Django 3.2.3 on 2021-09-26 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_registro_subkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='subkey',
        ),
        migrations.AlterField(
            model_name='registro',
            name='key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.subllaveregistro'),
        ),
    ]
