# Generated by Django 3.2.3 on 2021-09-27 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20210926_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='usuario_pc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
