# Generated by Django 3.2.3 on 2021-09-27 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_registro_usuario_pc'),
    ]

    operations = [
        migrations.AddField(
            model_name='llaveregistro',
            name='nombre_subllaves',
            field=models.BooleanField(default=False),
        ),
    ]
