# Generated by Django 3.2.3 on 2021-10-13 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20211001_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoevidencia',
            name='nombre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.estadoevidencia'),
        ),
    ]
